// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC95rHFgGZHS10VVblyIFU4NM1asn6uvxs',
    appId: '1:861387051087:web:da71e26ca03b29edfc5a3a',
    messagingSenderId: '861387051087',
    projectId: 'fir-ppb-cb2ec',
    authDomain: 'fir-ppb-cb2ec.firebaseapp.com',
    storageBucket: 'fir-ppb-cb2ec.appspot.com',
    measurementId: 'G-8M9RC5S1X7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsuqxfzUKh0TfvvNwqvy7IF2JXZl86kAY',
    appId: '1:861387051087:android:8235da9f6df50da9fc5a3a',
    messagingSenderId: '861387051087',
    projectId: 'fir-ppb-cb2ec',
    storageBucket: 'fir-ppb-cb2ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaGV7MWfvmn5SOOlbMWohmt6AEVUVsWk8',
    appId: '1:861387051087:ios:5eeef5c5593f4177fc5a3a',
    messagingSenderId: '861387051087',
    projectId: 'fir-ppb-cb2ec',
    storageBucket: 'fir-ppb-cb2ec.appspot.com',
    iosBundleId: 'com.example.firebasePpb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaGV7MWfvmn5SOOlbMWohmt6AEVUVsWk8',
    appId: '1:861387051087:ios:5eeef5c5593f4177fc5a3a',
    messagingSenderId: '861387051087',
    projectId: 'fir-ppb-cb2ec',
    storageBucket: 'fir-ppb-cb2ec.appspot.com',
    iosBundleId: 'com.example.firebasePpb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC95rHFgGZHS10VVblyIFU4NM1asn6uvxs',
    appId: '1:861387051087:web:07dbc5ee70167e10fc5a3a',
    messagingSenderId: '861387051087',
    projectId: 'fir-ppb-cb2ec',
    authDomain: 'fir-ppb-cb2ec.firebaseapp.com',
    storageBucket: 'fir-ppb-cb2ec.appspot.com',
    measurementId: 'G-04D0LY2858',
  );
}
